name: Cypress Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run test:allure -- --browser chrome
        env:
          CYPRESS_LOGIN: ${{ secrets.CYPRESS_LOGIN }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_pageLoadTimeout: 300000
          CYPRESS_viewportWidth: 1280
          CYPRESS_viewportHeight: 720
          CYPRESS_chromeWebSecurity: false
